<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>352ee1ea-32b1-4f3b-a871-36d91fd60700</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_fliese</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[7]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#DekorHolzart_id &gt; [class="filter-item"]:nth-child(3) &gt; [class="filter-item-name"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Fliese')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Fliese</value>
        <webElementGuid>eec3cd26-7025-4e20-8f14-3a88ca4bbfce</webElementGuid>
    </webElementProperties>
</WebElementEntity>