<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>228629d7-41a4-42ce-8f5b-d9019a160c20</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_collapseeditnewaddressbtn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[6]/div[2]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#collapseEditNewAddressBTN</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'collapseEditNewAddressBTN') and equals(@text,'Neue Adresse hinzuf\xfcgen')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Neue Adresse hinzuf\xfcgen"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>collapseEditNewAddressBTN</value>
        <webElementGuid>38c9bccd-e7b4-422f-8445-e6e87971b6fb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Neue Adresse hinzufügen</value>
        <webElementGuid>38c9bccd-e7b4-422f-8445-e6e87971b6fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>