<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d0fce227-4d59-4d0c-bc06-a9b82d341c43</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_zoi_techcon_gmbh</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/h2[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dismissable-company\\ -company\\ ps-relative\\ js-dismiss-overlay-container\\ p24\\ pr32\\ bb\\ bc-black-100"]:nth-child(1) [class="s-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Zoi TechCon GmbH')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=link[name=\\"Zoi TechCon GmbH\\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Zoi TechCon GmbH</value>
        <webElementGuid>3256e0a4-f8e4-42b6-ac91-80e323691e38</webElementGuid>
    </webElementProperties>
</WebElementEntity>