<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f975a267-aecf-4f41-a6b8-b7e7775e999f</elementGuidId>
    <imagePath></imagePath>
    <name>svg_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/span[1]/svg[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="button"]:nth-child(4) &gt; [class="svg-icon\\ iconClear"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["#company-search-form &gt;&gt; internal:role=button &gt;&gt; nth=0"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>