<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0235a60-23cc-4298-9b43-310d317777f0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_verf_gbar_in_filiale_bochum_filiale_n</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[20]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#Stock17c_id &gt; [class="filter-item"]:nth-child(2) &gt; [class="filter-item-name"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'verf\xfcgbar in Filiale Bochum\n\xa0(Filiale \xe4ndern)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>verfügbar in Filiale Bochum
         (Filiale ändern)</value>
        <webElementGuid>68349b90-87c5-4544-a956-bd0c1368e559</webElementGuid>
    </webElementProperties>
</WebElementEntity>