<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f0a252d7-9ea0-4a77-bf11-da3f51c8edf3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_vinylb_den</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[6]/div[2]/div[1]/ul[1]/li[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide04-slide01 &gt; [class="content-card\\ col-xs-12\\ col-sm-3\\ col-md-3"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'VINYLB\xd6DEN')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Vinylb\xf6den \ue092"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>VINYLBÖDEN</value>
        <webElementGuid>eec3cd26-7025-4e20-8f14-3a88ca4bbfce</webElementGuid>
    </webElementProperties>
</WebElementEntity>