<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>13903d8d-7b59-4f91-ab32-220e51ffe737</elementGuidId>
    <imagePath></imagePath>
    <name>button_filiale_w_hlen</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[2]/div[3]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="store-card-module\\ js-store-2\\ js-store-card"] [class="store-card-module__select-btn\\ btn\\ btn-default\\ js-select-store"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'FILIALE W\xc4HLEN')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.store-card-module__select-btn &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>FILIALE WÄHLEN</value>
        <webElementGuid>d247eec4-2cb7-4c68-b7b6-6ab5b3dde5e2</webElementGuid>
    </webElementProperties>
</WebElementEntity>