<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a23cc9c3-e98f-4983-9bc0-893bdcb0becd</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_klicken</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[14]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#Verlegetechnik_id &gt; [class="filter-item"]:nth-child(2) &gt; [class="filter-item-name"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'klicken')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>klicken</value>
        <webElementGuid>68349b90-87c5-4544-a956-bd0c1368e559</webElementGuid>
    </webElementProperties>
</WebElementEntity>