<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e363750e-db80-4200-adbe-63d2fcb20c05</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_mehr_artikel_anzeigen</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[4]/div[14]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-list-item\\ paging-tile\\ col-lg-3\\ col-md-4\\ col-sm-4\\ col-xs-12\\ grid-view"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'MEHR ARTIKEL ANZEIGEN')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Mehr Artikel anzeigen \ue092"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>MEHR ARTIKEL ANZEIGEN</value>
        <webElementGuid>eec3cd26-7025-4e20-8f14-3a88ca4bbfce</webElementGuid>
    </webElementProperties>
</WebElementEntity>