<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a8dfd1e4-841a-43ae-822a-766b34a0e8f1</elementGuidId>
    <imagePath></imagePath>
    <name>img_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[11]/div[2]/div[1]/div[1]/div[4]/picture[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#lg-item-1-7 [class="lg-object\\ lg-image"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#lg-item-1-7 &gt;&gt; internal:role=img[name="Rigid-Vinyl BoDomo Premium"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>