<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>16af5183-cb7b-48cd-92ff-11f29e3d658d</elementGuidId>
    <imagePath></imagePath>
    <name>h4_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[1]/div[2]/form[1]/div[2]/div[1]/div[1]/div[1]/div[2]/label[1]/div[3]/h4[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="mineral-estrich"] h4</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="Estrich, Beton"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>