<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>75c1219d-6efc-475c-a75a-b378443df93d</elementGuidId>
    <imagePath></imagePath>
    <name>img_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[1]/div[2]/form[1]/div[6]/div[1]/div[1]/div[2]/label[3]/div[2]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="format-plank-wo-joint"] img</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>label &gt;&gt; internal:has-text="Diele ohne Fuge"i &gt;&gt; internal:role=img</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>