<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>003887f2-9547-493d-a977-64a483f7f54e</elementGuidId>
    <imagePath></imagePath>
    <name>img_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/label[1]/div[2]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="damproom-no"] img</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>label &gt;&gt; internal:has-text="Wohnraum Wohn- und"i &gt;&gt; internal:role=img</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>