<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>33d1107e-b542-4564-b0fe-89be0d7d5666</elementGuidId>
    <imagePath></imagePath>
    <name>body_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>