<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e1f9d887-a426-4e96-8eae-e5aef18b9c39</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_vinylb_den</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[7]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide04-slide01 a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Vinylb\xf6den')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#splide04-slide01 &gt;&gt; internal:role=link[name="Vinylb\xf6den"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Vinylböden</value>
        <webElementGuid>eec3cd26-7025-4e20-8f14-3a88ca4bbfce</webElementGuid>
    </webElementProperties>
</WebElementEntity>