<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>66f197c2-f975-4619-b854-2b332c13334e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[14]/div[1]/div[2]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fc-timegrid-col\\ fc-day\\ fc-day-sun\\ fc-day-past\\ fc-resource"]:nth-child(14) [class="fc-timegrid-event-harness"]:nth-child(3) &gt; [class="fc-timegrid-event\\ fc-v-event\\ fc-timegrid-event-condensed\\ fc-event\\ fc-event-draggable\\ fc-event-resizable\\ fc-event-start\\ fc-event-end\\ fc-event-past\\ undefined"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text="John Alexander"i &gt;&gt; nth=3</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>