<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b89fd165-a480-4298-b9d9-542d029497fe</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_hell</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/nav[1]/div[1]/ul[1]/div[1]/ul[1]/li[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ld_nav__offcanvas\\ ld_nav__subcategory-container\\ js-flyout-container\\ offcanvas\\ is-left\\ is-open"] [class="ld_nav__offcanvas__category-li\\ \\ main-navigation-level1\\#-item"]:nth-child(2) [class="ld_nav__offcanvas__category-li\\ animated-link-parent\\ main-navigation-level2\\#-item"]:nth-child(1) &gt; [class="ld_nav__offcanvas__category-link\\ animated-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'hell')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="hell"i] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>hell</value>
        <webElementGuid>d247eec4-2cb7-4c68-b7b6-6ab5b3dde5e2</webElementGuid>
    </webElementProperties>
</WebElementEntity>