<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>08a3238a-a12b-4203-8834-44a98e61800b</elementGuidId>
    <imagePath></imagePath>
    <name>li_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/nav[1]/div[1]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="animated-link-parent\\ cat-\\ Laminat-navi\\ js-subcategory-flyout"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ld_nav__offcanvas-list &gt; li &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>