<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1142945c-780b-4c94-8cf6-30703501b3fb</elementGuidId>
    <imagePath></imagePath>
    <name>button_save_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[1]/div[2]/div[2]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeMedium\\ MuiButton-containedSizeMedium\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeMedium\\ MuiButton-containedSizeMedium\\ css-1pvug0y"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Save')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Save"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Save</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
</WebElementEntity>