<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4e38555f-5e98-49ee-8d1c-e001cf15c933</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiGrid-root\\ MuiGrid-container\\ jss2884\\ \\ css-sfdl7"] [class="MuiButtonBase-root\\ MuiButton-root\\ MuiButton-outlined\\ MuiButton-outlinedPrimary\\ MuiButton-sizeSmall\\ MuiButton-outlinedSizeSmall\\ MuiButtonGroup-grouped\\ MuiButtonGroup-groupedHorizontal\\ MuiButtonGroup-groupedOutlined\\ MuiButtonGroup-groupedOutlinedHorizontal\\ MuiButtonGroup-groupedOutlinedPrimary\\ MuiButton-root\\ MuiButton-outlined\\ MuiButton-outlinedPrimary\\ MuiButton-sizeSmall\\ MuiButton-outlinedSizeSmall\\ css-ippbir"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; .MuiGrid-root &gt; .MuiButtonGroup-root &gt; button:nth-child(2)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
</WebElementEntity>