<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c1900020-0d2b-4694-890b-2fc7107dea54</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_membership_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\\ MuiButton-root\\ MuiButton-outlined\\ MuiButton-outlinedPrimary\\ MuiButton-sizeMedium\\ MuiButton-outlinedSizeMedium\\ MuiButton-root\\ MuiButton-outlined\\ MuiButton-outlinedPrimary\\ MuiButton-sizeMedium\\ MuiButton-outlinedSizeMedium\\ jss375\\ css-n9rec5"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Add Membership')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Add Membership"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add Membership</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
</WebElementEntity>