<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a181f3ac-ca51-45bc-9889-7abb503d8f09</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_restposten_rigid_vinyl_eiche_frankfurt</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[4]/div[11]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-list-item\\ col-lg-3\\ col-md-4\\ col-sm-4\\ col-xs-12\\ grid-view"]:nth-child(11) [class="product-title\\ producttile-productlink\\ list-view"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'RESTPOSTEN\nRigid-Vinyl Eiche Frankfurt\n\nSet mit integrierter D\xe4mmung und Fu\xdfleiste')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="RESTPOSTEN Rigid-Vinyl Eiche"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>RESTPOSTEN
        Rigid-Vinyl Eiche Frankfurt
        
        Set mit integrierter Dämmung und Fußleiste</value>
        <webElementGuid>d247eec4-2cb7-4c68-b7b6-6ab5b3dde5e2</webElementGuid>
    </webElementProperties>
</WebElementEntity>