<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>be6488f2-b33a-4453-81cb-82a85d8e9c7e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[4]/div[12]/div[1]/div[1]/div[2]/div[2]/ul[1]/li[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide09-slide01 [class="producttile-productlink"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Rigid-Vinyl BoDomo Klassik Makula Stahl Produktbild"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>