<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>222880b5-936d-4202-b84c-7c506b17e3d8</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_rigid_vinyl_glasgow_set_mit_integrierte</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-list-item\\ col-lg-3\\ col-md-4\\ col-sm-4\\ col-xs-12\\ grid-view"]:nth-child(2) [class="product-title\\ producttile-productlink\\ list-view"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Rigid-Vinyl Glasgow\n\nSet mit integrierter D\xe4mmung und Fu\xdfleiste')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Rigid-Vinyl Glasgow Set mit"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Rigid-Vinyl Glasgow
        
        Set mit integrierter Dämmung und Fußleiste</value>
        <webElementGuid>68349b90-87c5-4544-a956-bd0c1368e559</webElementGuid>
    </webElementProperties>
</WebElementEntity>