<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3ae6c85a-fde2-4bb1-ac98-2fb258d0b817</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_hell</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/nav[1]/div[1]/ul[1]/div[1]/ul[1]/li[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ld_nav__offcanvas\\ ld_nav__subcategory-container\\ js-flyout-container\\ offcanvas\\ is-left\\ is-open"] [class="ld_nav__offcanvas__category-li\\ \\ main-navigation-level1\\#-item"]:nth-child(2) [class="ld_nav__offcanvas__category-li\\ animated-link-parent\\ main-navigation-level2\\#-item"]:nth-child(1) &gt; [class="ld_nav__offcanvas__category-link\\ animated-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'hell')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>hell</value>
        <webElementGuid>eec3cd26-7025-4e20-8f14-3a88ca4bbfce</webElementGuid>
    </webElementProperties>
</WebElementEntity>