<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>94c6aa41-1eea-43ab-abd4-08ae759a6a5d</elementGuidId>
    <imagePath></imagePath>
    <name>li_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[4]/div[2]/div[1]/div[2]/div[3]/ul[1]/li[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="product-list-item\\ col-lg-3\\ col-md-4\\ col-sm-4\\ col-xs-12\\ grid-view"]:nth-child(2) [class="product-bullets"] li:nth-child(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Geeignet f\xfcr Fu\xdfbodenheizungen"i &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>