<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8bdb2a06-3646-488a-bca2-9039ce530f38</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/h3[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="filter-headline\\ filter-sorting-headline\\ collapsed"] &gt; [class="glyphicon\\ pull-right\\ glyphicon-chevron-right\\ glyphicon-chevron-down"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>