<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74e39ecb-537d-4e43-b8e0-e96c334ff97c</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[5]/h3[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="filter-group"]:nth-child(5) [class="glyphicon\\ pull-right\\ glyphicon-chevron-right\\ glyphicon-chevron-down"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>