<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e0ab72e5-30f7-4ac1-91b0-201eaa3f777d</elementGuidId>
    <imagePath></imagePath>
    <name>svg_object_8</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[4]/div[6]/div[1]/div[1]/div[2]/div[1]/button[2]/svg[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide03 [class="splide__arrow\\ splide__arrow--next"] &gt; svg</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#splide03 &gt;&gt; internal:label="Next slide"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>