<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>535fbf52-1c0a-4f78-a141-2d429e805fab</elementGuidId>
    <imagePath></imagePath>
    <name>img_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[3]/div[2]/div[2]/div[1]/div[2]/ul[1]/li[6]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide02-slide06 [class="square\\ product-image"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=img[name="Laminat BoDomo Klassik First Eiche Produktbild rendering7 zoom"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>