<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cacbd4f5-e6fd-4a96-b4d0-a315adf481a0</elementGuidId>
    <imagePath></imagePath>
    <name>li_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/nav[1]/div[1]/ul[1]/li[8]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="animated-link-parent\\ cat-\\ Sale-navi\\ js-subcategory-flyout"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=navigation &gt;&gt; li &gt;&gt; internal:has-text="Sale"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>