<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>638a84c1-8baf-48d3-b8c7-49344b11308d</elementGuidId>
    <imagePath></imagePath>
    <name>button_sendorder</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[6]/form[1]/div[2]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-lg\\ btn-block\\ btn-primary\\ btn-send-order"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'sendOrder') and equals(@type,'submit') and equals(@text,'JETZT RESERVIEREN')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="JETZT RESERVIEREN"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>sendOrder</value>
        <webElementGuid>d247eec4-2cb7-4c68-b7b6-6ab5b3dde5e2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>JETZT RESERVIEREN</value>
        <webElementGuid>d247eec4-2cb7-4c68-b7b6-6ab5b3dde5e2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>d247eec4-2cb7-4c68-b7b6-6ab5b3dde5e2</webElementGuid>
    </webElementProperties>
</WebElementEntity>