<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>57892aa9-6656-46f5-8d6e-d41039282e51</elementGuidId>
    <imagePath></imagePath>
    <name>fieldset_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[3]/div[3]/div[1]/form[1]/div[2]/div[1]/fieldset[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="checkout-widget-box\\ padding\\ base-2"] fieldset:nth-child(5)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>fieldset &gt;&gt; internal:has-text="Stra\xdfe und Hausnummer*"i &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>