<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4e1669c9-8589-442d-936b-82b4bb1c422a</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[6]/div[1]/form[1]/ul[1]/li[3]/div[1]/label[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#paymentOption_vyQKAQNEzIMAAAF3kxQCu_Oh</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=tab[name="Kreditkarte"i] &gt;&gt; internal:label="Kreditkarte"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>