<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9bc749f3-d172-4019-9f90-f9bd86a95d5e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_in_den_warenkorb_kostenlose_d_mmung_un</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[3]/div[4]/div[2]/div[1]/div[4]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ addToCartButton\\ btn-lg\\ btn-block\\ btn-primary\\ configurator-dialog"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'IN DEN WARENKORB\n+ kostenlose D\xe4mmung und Fu\xdfleisten w\xe4hlen')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="In den Warenkorb + kostenlose"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>IN DEN WARENKORB
        + kostenlose Dämmung und Fußleisten wählen</value>
        <webElementGuid>38c9bccd-e7b4-422f-8445-e6e87971b6fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>