<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6318c8ff-ec26-4824-8c4a-99b3cfe7136f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_alle_sale_artikel</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/nav[1]/div[1]/ul[1]/div[8]/ul[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ld_nav__offcanvas\\ ld_nav__subcategory-container\\ js-flyout-container\\ offcanvas\\ is-left\\ is-open"] [class="animated-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Alle Sale Artikel')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Alle Sale Artikel"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Alle Sale Artikel</value>
        <webElementGuid>68349b90-87c5-4544-a956-bd0c1368e559</webElementGuid>
    </webElementProperties>
</WebElementEntity>