<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ea504529-79a4-482f-905e-61c052025731</elementGuidId>
    <imagePath></imagePath>
    <name>img_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[3]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[2]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide02-slide02 [class="square\\ product-image"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=img[name="Rigid-Vinyl Decoflooring Fliese Braunschweig Produktbild Schlafzimmer - Urban"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>