<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c6dd4fed-03ea-4d76-86e5-fe26905b0323</elementGuidId>
    <imagePath></imagePath>
    <name>img_object_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[1]/picture[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="enhanced-image\\ store-einstiegsteaser\\ promo-teaser\\ "]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=img[name="Wir r\xe4umen auf. Sie r\xe4umen ab!"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>