<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>044b0ac2-823e-4ce0-89c3-7cc6f4b06be3</elementGuidId>
    <imagePath></imagePath>
    <name>img_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[3]/div[2]/div[2]/div[1]/div[2]/ul[1]/li[3]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide02-slide03 [class="square\\ product-image"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=img[name="Parkett BoDomo Premium Florenz Produktbild Wohnzimmer - Urban mit Wohnwand zoom"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>