<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b1627ecd-0bfa-4e09-93f6-1debd43074ba</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[1]/h3[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="filter-headline\\ filter-sorting-headline\\ collapsed"] &gt; [class="glyphicon\\ pull-right\\ glyphicon-chevron-right\\ glyphicon-chevron-down"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="Sortieren nach \ue114"i] &gt;&gt; span</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>