<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2caf9da1-d84f-4107-838d-0d1d0b3504e4</elementGuidId>
    <imagePath></imagePath>
    <name>button_close_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[1]/div[2]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiGrid-root\\ MuiGrid-item\\ css-1wxaqej"] &gt; [class="MuiButtonBase-root\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeMedium\\ MuiButton-containedSizeMedium\\ MuiButton-root\\ MuiButton-contained\\ MuiButton-containedPrimary\\ MuiButton-sizeMedium\\ MuiButton-containedSizeMedium\\ css-1pvug0y"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Close')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Close"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Close</value>
        <webElementGuid>65043cfb-8800-413a-b10c-b06a5ad817f9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>65043cfb-8800-413a-b10c-b06a5ad817f9</webElementGuid>
    </webElementProperties>
</WebElementEntity>