<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9741740d-6981-4340-afb4-d2e2ef54fe8b</elementGuidId>
    <imagePath></imagePath>
    <name>button_scrollable_auto_tab_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/p[1]/div[1]/div[1]/div[1]/div[1]/button[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'scrollable-auto-tab-3') and equals(@type,'button') and equals(@text,'REMAINING CREDITS')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>scrollable-auto-tab-3</value>
        <webElementGuid>e0ffd749-c1dc-47e5-afcc-f064aa685d0f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>REMAINING CREDITS</value>
        <webElementGuid>e0ffd749-c1dc-47e5-afcc-f064aa685d0f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>e0ffd749-c1dc-47e5-afcc-f064aa685d0f</webElementGuid>
    </webElementProperties>
</WebElementEntity>