<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ff16950b-77a8-4f73-a1d6-226c7ad6a548</elementGuidId>
    <imagePath></imagePath>
    <name>button_scrollable_auto_tab_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/header[1]/div[1]/div[1]/div[1]/button[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#scrollable-auto-tab-4</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'scrollable-auto-tab-4') and equals(@type,'button') and equals(@text,'ALERTS &amp; NOTES')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=tab[name="Alerts &amp; Notes"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>scrollable-auto-tab-4</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>ALERTS &amp; NOTES</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
</WebElementEntity>