<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>133ef342-28cf-44d2-ba48-b208b42dbbeb</elementGuidId>
    <imagePath></imagePath>
    <name>button_scrollable_auto_tab_2_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/p[1]/div[1]/div[1]/div[1]/div[1]/button[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'scrollable-auto-tab-2') and equals(@type,'button') and equals(@text,'USED CREDITS')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>scrollable-auto-tab-2</value>
        <webElementGuid>318eb8bc-aa03-430e-b211-f956b4d82220</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>USED CREDITS</value>
        <webElementGuid>318eb8bc-aa03-430e-b211-f956b4d82220</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>318eb8bc-aa03-430e-b211-f956b4d82220</webElementGuid>
    </webElementProperties>
</WebElementEntity>