<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5c4f2ade-6ff3-40a4-92a8-157a4634b63e</elementGuidId>
    <imagePath></imagePath>
    <name>button_scrollable_auto_tab_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/header[1]/div[1]/div[1]/div[1]/button[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'scrollable-auto-tab-4') and equals(@type,'button') and equals(@text,'ALERTS &amp; NOTES')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>scrollable-auto-tab-4</value>
        <webElementGuid>701186b8-9d5f-4213-8821-baad3942493b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>ALERTS &amp; NOTES</value>
        <webElementGuid>701186b8-9d5f-4213-8821-baad3942493b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>701186b8-9d5f-4213-8821-baad3942493b</webElementGuid>
    </webElementProperties>
</WebElementEntity>