<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e1fd84cc-bd2b-482e-9edc-dc63de48a5fd</elementGuidId>
    <imagePath></imagePath>
    <name>input_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\\ MuiCheckbox-root\\ MuiCheckbox-colorPrimary\\ PrivateSwitchBase-root\\ MuiCheckbox-root\\ MuiCheckbox-colorPrimary\\ MuiCheckbox-root\\ MuiCheckbox-colorPrimary\\ jss138\\ css-113n9dd"] &gt; [class="PrivateSwitchBase-input\\ css-1m9pwf3"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=row[name="Red Light Therapy 42.00"i] &gt;&gt; internal:role=checkbox</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>0d464a8d-34c5-41fc-8303-8d1741ec96c5</webElementGuid>
    </webElementProperties>
</WebElementEntity>