<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>416bab3e-8138-43fa-82bd-5a1a572c569d</elementGuidId>
    <imagePath></imagePath>
    <name>select_status</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[5]/div[1]/p[1]/div[1]/div[2]/div[2]/div[1]/p[1]/div[1]/div[3]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/span[1]/div[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiInputBase-root\\ MuiInput-root\\ MuiInputBase-colorPrimary\\ MuiInputBase-fullWidth\\ Mui-focused\\ MuiNativeSelect-root\\ jss192\\ css-y75buu"] &gt; [class="MuiNativeSelect-select\\ MuiNativeSelect-standard\\ MuiInputBase-input\\ MuiInput-input\\ css-1vynybe"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'Status')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=row[name="Lead Follow-up 04/06/2024"i] &gt;&gt; select[name="Status"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>Status</value>
        <webElementGuid>c911dfd2-17b0-4175-8ded-a5e925fa8cbd</webElementGuid>
    </webElementProperties>
</WebElementEntity>