<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>91aadf46-43e9-4df8-9753-4f7a75b2da1a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_fu_leiste_klassik_h_he_40_mm</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/nav[1]/div[1]/ul[1]/div[6]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ld_nav__offcanvas\\ ld_nav__subcategory-container\\ js-flyout-container\\ offcanvas\\ is-left\\ firstLevelLink\\ is-open"] [class="ld_nav__offcanvas__category-li\\ \\ main-navigation-level1\\#-item"]:nth-child(2) &gt; [class="ld_nav__offcanvas__category-link\\ animated-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Fu\xdfleiste Klassik - H\xf6he 40 mm')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Fu\xdfleiste Klassik - H\xf6he 40 mm"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Fußleiste Klassik - Höhe 40 mm</value>
        <webElementGuid>68349b90-87c5-4544-a956-bd0c1368e559</webElementGuid>
    </webElementProperties>
</WebElementEntity>