<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e2daed7f-29e8-4b5c-b273-89f91488e010</elementGuidId>
    <imagePath></imagePath>
    <name>img_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[3]/div[2]/div[2]/div[1]/div[2]/ul[1]/li[3]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide02-slide03 [class="square\\ product-image"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=img[name="Rigid-Vinyl BoDomo Exquisit Vancouver grey Produktbild Wohnzimmer - Urban mit"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>