<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6879f819-4326-4dab-acc7-26fec33010e7</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_wei</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[11]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="filter-item\\ filter-colour"]:nth-child(1) &gt; [class="filter-item-name\\ filter-swatch"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Wei\xdf')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[title="Wei\xdf (8)"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Weiß</value>
        <webElementGuid>68349b90-87c5-4544-a956-bd0c1368e559</webElementGuid>
    </webElementProperties>
</WebElementEntity>