<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3ba53b9e-89e5-4398-8f84-f18bd560210f</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[15]/h3[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="filter-group"]:nth-child(15) [class="glyphicon\\ pull-right\\ glyphicon-chevron-right\\ glyphicon-chevron-down"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>