<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bb3e1d6d-2484-4842-974a-6b5d9a0561d3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_breitdiele</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/nav[1]/div[1]/ul[1]/div[1]/ul[1]/li[3]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ld_nav__offcanvas\\ ld_nav__subcategory-container\\ js-flyout-container\\ offcanvas\\ is-left\\ is-open"] [class="ld_nav__offcanvas__category-li\\ \\ main-navigation-level1\\#-item"]:nth-child(4) [class="ld_nav__offcanvas__category-li\\ animated-link-parent\\ main-navigation-level2\\#-item"]:nth-child(3) &gt; [class="ld_nav__offcanvas__category-link\\ animated-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Breitdiele')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Breitdiele"i] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Breitdiele</value>
        <webElementGuid>eec3cd26-7025-4e20-8f14-3a88ca4bbfce</webElementGuid>
    </webElementProperties>
</WebElementEntity>