<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>99a1993d-87d8-4ed1-b8c2-5290149e0d08</elementGuidId>
    <imagePath></imagePath>
    <name>button_filtern_sortieren</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[4]/div[1]/div[1]/div[2]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="filter-container__button"]:nth-child(2) &gt; [class="btn\\ filter-open-btn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Filtern &amp; Sortieren')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Filtern &amp; Sortieren</value>
        <webElementGuid>68349b90-87c5-4544-a956-bd0c1368e559</webElementGuid>
    </webElementProperties>
</WebElementEntity>