<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7729559f-0b6e-4b02-b068-d3973c4216d0</elementGuidId>
    <imagePath></imagePath>
    <name>button_ok_weiter_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[15]/div[1]/div[2]/form[1]/div[6]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="floor-advisor-step-6\\ offcanvas\\ is-right\\ is-open"] [class="btn\\ btn-primary\\ next-step"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'OK - WEITER')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.floor-advisor-step-6 &gt; .floor-advisor__footer &gt; .btn</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>OK - WEITER</value>
        <webElementGuid>38c9bccd-e7b4-422f-8445-e6e87971b6fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>