<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de0623a8-7745-4c63-b571-70bd31800def</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[15]/div[1]/div[2]/form[1]/div[4]/div[1]/div[1]/div[1]/label[1]/div[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="heating_no"] &gt; [class="floor-advisor-content-element__text"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.floor-advisor-step-4 &gt; .floor-advisor__body &gt; .floor-advisor__content &gt; .floor-advisor-content__elements &gt; label &gt; .floor-advisor-content-element__text</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>