<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>69abd096-c8cc-4060-a22b-40714f06abd3</elementGuidId>
    <imagePath></imagePath>
    <name>img_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[3]/div[2]/div[1]/div[2]/div[2]/ul[1]/li[1]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#splide01-slide01 img</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#splide01-slide01 [data-test="true"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>