<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>14830400-9635-4c3f-8262-2789305a1a00</elementGuidId>
    <imagePath></imagePath>
    <name>li_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[15]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/label[1]/div[3]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="damproom-no"] li:nth-child(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Wohn- und Essbereich"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>