<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cac3aefd-7e58-4c4f-9ce5-613eb31d15a3</elementGuidId>
    <imagePath></imagePath>
    <name>p_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[16]/div[1]/div[1]/div[2]/div[1]/p[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ld-Free-html\\ \\a flooradvisor-modal-residual-moisture"] &gt; [class="fa-modal-text"]:nth-child(3)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Bitte beachten Sie, dass vor"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>